server:
  port: 5000
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}

  session:
    store-type: none

  redis:
    host: localhost
    port: 6379
    
  
  # jpa:
  #   open-in-view: false
  #   hibernate:
  #     ddl-auto: create
      
    # properties:
    #   '[hibernate.format_sql]': true    
  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.springframework.boot.web]': INFO
    #'[org.springframework.web]': DEBUG
    


