server:
  port: 8001
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL # MariaDB 가 안됨
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always

logging:
  level:
    root: DEBUG
    #'[org.hibernate]': DEBUG - 하이버네이트 사용 안함